### ISSUE TITLE
Unable to find License details

### ISSUE THREAD

**Issue by metaprem** [josephwegner/simple-api#10]
Could not find license details in readme or a separate license file.

For example, please see the readme file at https://github.com/saintedlama/passport-local-mongoose#license , the readme file mentions the license and points to it.

Mentioning the license at end of readme seems to be becoming the norm.

**Comment by josephwegner** [comment]
That's a great idea!  What license would you like Simple API to have?  Drop it in a pull request, if you're in a rush.

**Comment by metaprem** [comment]
no hurry. sent pull request.

**Comment by josephwegner** [comment]
Thanks for the PR!  I added a LICENSE file as well, so it can be found in both places.
