### ISSUE TITLE
Convenience Response Functions

### ISSUE THREAD

**Issue by josephwegner** [josephwegner/simple-api#4]
It's a huge pain to write things like

```
res.statusCode = 500;
res.end(JSON.stringify({
    error: true,
    message: "You Suck!"
});
```

every time we have an error.  It also sucks for every other common type of response.  We need convenience functions for these.

I'm thinking
- internalError (optional messages and status codes)
- respond (accepts string or object for message and optional status code.  Objects will be JSON stringified.  Status code defaults to 200)
- notAuth (Same as respond, but the param is optional.  Defaults to some generic auth JSON)
- notAvailable (optional message or object.  Default is just blank 404)

Please add to this list.

**Comment by jessepollak** [comment]
notAuth should return a 403 with a message, I think (although, there's no real consensus on this).

Others
- redirect (should be able to return 302 or 301)

**Comment by josephwegner** [comment]
Implemented here: https://github.com/josephwegner/simple-api/commit/df4f2227b6571225040d7ce9295c1a0928eed108

They new convenience functions seem to be functionally complete, but I'm having trouble with the tests.  I think it's a testing framework issue rather than a simple-api issue.

Jesse, if you're interested feel to free to checkout this branch and test or just do a code review and provide feedback.  Otherwise I will merge it into master as soon as I can get the tests to pass.

Note, the README hasn't been updated in this branch yet, so you'll want to read the diff to see how things work.  Essentially all the new funcs are on `this.responses` and accept parameters like `this.responses.response(res, message, statusCode);`

Let me know if you have issues or think any terminology/functionality should be changed.

**Comment by jessepollak** [comment]
I'll look into this tonight/tomorrow morning!

**Comment by josephwegner** [comment]
There are few things more frustrating that unit tests breaking when it's unrelated to the code it's supposed to be testing...

I've posted an SO question about the issue, and can't merge this in until the tests pass.  This is also blocking the remaining issues, so I'm sitting on my hands with simple-api for a bit.

http://stackoverflow.com/questions/18616329/mocha-requires-me-to-read-http-request-body

**Comment by jessepollak** [comment]
Interesting stuff.

**Comment by josephwegner** [comment]
That SO answer still isn't my issue.  Apparently I went too far down a rabbit hole and started introducing unrelated bugs.

**Comment by josephwegner** [comment]
So, apparently Node.js hangs up if you don't act like you're parsing the data on a GET request.

I'm guessing that it drops responses onto a buffer while it waits for you to manage them..  Since all of the tests request happen so fast, that buffer is filling up and hanging the HTTP responses.

I put in fake response listeners so that the tests would pass: 43927d7402efbfff5e6ad0ba2c469e1497a4b533

@jessepollak, I'm going to close this tomorrow unless you have some feedback.  I've updated the README if you just want to peruse that.

**Comment by jessepollak** [comment]
looking over it right now.

**Comment by jessepollak** [comment]
I'm just going to post thoughts, feel free to dismiss them.

For responses, do we want to have a default content-type (JSON)?

**Comment by jessepollak** [comment]
Added some line comments. I'd be happy to make those changes, if you want me to.

Otherwise, tests pass and code looks great, so :shipit:

**Comment by josephwegner** [comment]
If you want to do those changes before morning comes, feel free.  Otherwise I will knock them out and ship the latest to npm.

**Comment by josephwegner** [comment]
@jessepollak I did the content type fix this morning, but I did not do the other ones.  I'm still on the fence about both of them.  If you want to do the update I'd be happy to pull the changes in and release a 0.1.1.

Up to you.
