### ISSUE TITLE
Controller should have access to base API class

### ISSUE THREAD

**Issue by jessepollak** [josephwegner/simple-api#5]
This is important for things like generating URLs because you need access to the API prefix.

In general, as we talked about yesterday, this may involve restructuring the controllers.

**Comment by josephwegner** [comment]
I noticed this this morning:

https://github.com/josephwegner/simple-api/blob/master/lib/Controller.js#L2

Can you confirm that the controller doesn't have an `api` key?

**Comment by jessepollak** [comment]
I'm pretty certain.

I think the problem is that when you create the controller like [this](https://github.com/josephwegner/cydoemus/blob/master/index.coffee#L21), what "feels" like the controller is actually just the configuration object, which doesn't have access to the full controller scope.

**Comment by josephwegner** [comment]
Odd.  Calling the action [like this](http://arstechnica.com/gadgets/2013/09/balky-carriers-and-slow-oems-step-aside-google-is-defragging-android/) should apply the correct scope.  I'll write some tests and figure out what's going on.

**Comment by jessepollak** [comment]
Wrong link?

**Comment by josephwegner** [comment]
Doh! (Although, that is a super interesting article...)

https://github.com/josephwegner/simple-api/blob/master/lib/simple-api.js#L110

**Comment by jessepollak** [comment]
That's true. I was having the problem in helpers, so it may have been that...

**Comment by josephwegner** [comment]
Hey Jesse,

It seems to be working for me both manually and in unit tests.  Unit test here: 9758a811dd0fe499a7959f50d696f530c2784b0e

If you can recreate the issue (or provide more details) I'd be glad to fix it.  Otherwise I'd like to close this issue.

**Comment by jessepollak** [comment]
Go ahead and close, I think it was a issue with the helpers.
