### ISSUE TITLE
Change language/format around "pieces"

### ISSUE THREAD

**Issue by jessepollak** [josephwegner/simple-api#6]
This should be able to be either an array or a "/" separated path.

I also think that pieces should be changed to something more intuitive like path.

**Comment by josephwegner** [comment]
Unrelated, but the `prefix` option on the API creation options does support array or string.  I will update controller routes so they are similar.

**Comment by josephwegner** [comment]
Here it is: 68856ce284a516e6a562a195d37b2d15e8cf34df

Gosh, that was such a simple fix.

@jessepollak Docs are updated and the code is merged into master.  I'll be closing this tomorrow unless I hear anything from you.

**Comment by jessepollak** [comment]
:thumbsup:
